### ISSUE TITLE
error in the tornado module

### ISSUE THREAD

**Issue by itslemcy** [sainipray/facedetect#1]
> traceback (most recent call last):
>       File "/usr/local/lib/python2.7/site-packages/tornado/websocket.py", line 415, in _run_callback
>         callback(*args, **kwargs)
>       File "liveface/websocket.py", line 25, in on_message
>         from main.detect import get_face_detect_data
>     ImportError: No module named main.detect

could you help me out?

**Comment by itslemcy** [comment]
> python liveface/websocket.py

i did everything precisely as described in the readme
tested on osx and ubuntu, same error

**Comment by sainipray** [comment]
Fixed above issue, take new clone and read docs
