### ISSUE TITLE
Python version required for this repo

### ISSUE THREAD

**Issue by RajeshKumarS** [sainipray/facedetect#8]
Is there any specific python version required for this repo? While trying out video option, I got this error message in base64_decode():

AttributeError: 'str' object has no attribute 'decode'

I am not able to run the image option also; get a POST error.

Thanks,

**Comment by sainipray** [comment]
@RajeshKumarS  Check this python2.7 version, I need to update for python3 version, if you can, create PR for this I'll merge in repo

**Comment by RajeshKumarS** [comment]
Thanks. It will be great to have this dependency mentioned in the readme. Please ignore if it is already mentioned and I missed it.

**Comment by RajeshKumarS** [comment]
A footnote:

Here are a few changes required in main/detect.py to make it work with Python 3.x:

1. Change

def base64_decode(data):
    format, imgstr = data.split(';base64,')
    return imgstr.decode('base64')

to

def base64_decode(data):
    format, imgstr = data.split(';base64,')
    return base64.b64decode(imgstr)

2. In detectImage(image), chnage

        encoded_string = base64.b64encode(buffer.getvalue())

to

        encoded_string = base64.b64encode(buffer.getvalue()).decode('utf-8')

Cheers,

**Comment by sainipray** [comment]
If you can release PR for this, I'll merge

**Comment by talhaanwarch** [comment]
i tried to move it to django 3 and python 3, but stuck at tornado web socket, because I don't know its concept
